python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_336_720 \
  --model SCSformer \
  --data ETTh2 \
  --trans_data True \
  --date_index 'HourOfDay'  \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 1024 \
  --d_ff 1024 \
  --des 'Exp' \
  --learning_rate 0.01 \
  --itr 1 \
  --train_epochs 10 \
  --patience 3 \
  --lradj type1 \
  --orgin_coef 0.0 \
  --revin_coef 1.0  \
  --convd_coef 1.0 \
  --kernel_size 1 \
  --w_lin 0.5


  
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_336_336 \
  --model SCSformer \
  --data ETTh2 \
  --trans_data True \
  --date_index 'HourOfDay'  \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 1024 \
  --d_ff 1024 \
  --des 'Exp' \
  --learning_rate 0.025 \
  --itr 1 \
  --train_epochs 10 \
  --patience 3 \
  --lradj type1 \
  --orgin_coef 0.0 \
  --revin_coef 1.0  \
  --convd_coef 1.0 \
  --kernel_size 1 \
  --w_lin 0.75   
  

  

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_336_192 \
  --model SCSformer \
  --data ETTh2 \
  --trans_data True \
  --date_index 'HourOfDay'  \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 1024 \
  --d_ff 1024 \
  --des 'Exp' \
  --learning_rate 0.01 \
  --itr 1 \
  --train_epochs 10 \
  --patience 3 \
  --lradj type1 \
  --orgin_coef 0.0 \
  --revin_coef 1.0  \
  --convd_coef 1.0 \
  --kernel_size 1 \
  --w_lin 0.5
  
  

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_336_96 \
  --model SCSformer \
  --data ETTh2 \
  --trans_data True \
  --date_index 'HourOfDay'  \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 1024 \
  --d_ff 1024 \
  --des 'Exp' \
  --learning_rate 0.025 \
  --itr 1 \
  --train_epochs 10 \
  --patience 3 \
  --lradj type1 \
  --orgin_coef 0.0 \
  --revin_coef 1.0  \
  --convd_coef 1.0 \
  --kernel_size 1 \
  --w_lin 0.5
